feat: Add the creation of 'Microsoft.DocumentDB/databaseAccounts/sqlRoleDefinitions' and ‘Microsoft.DocumentDB/databaseAccounts/sqlRoleAssignments’ and 'cosmos.properties.documentEndpoint'.
Azure/bicep-registry-modules pull request #2103
Opened 2024-05-31 08:02 UTC by zedy-wj

## Description

Fixes #1126 
## Pipeline Reference

| Pipeline |
| -------- |
|          |

## Type of Change

- [ ] Update to CI Environment or utlities (Non-module effecting changes)
- [ x] Azure Verified Module updates:
  - [ ] Bugfix containing backwards compatible bug fixes, and I have NOT bumped the MAJOR or MINOR version in `version.json`:
    - [ ] Someone has opened a bug report issue, and I have included "Closes #{bug_report_issue_number}" in the PR description.
    - [ ] The bug was found by the module author, and no one has opened an issue to report it yet.
  - [ ] Feature update backwards compatible feature updates, and I have bumped the MINOR version in `version.json`.
  - [ ] Breaking changes and I have bumped the MAJOR version in `version.json`.
  - [ ] Update to documentation

## Checklist

- [ x] I'm sure there are no other open Pull Requests for the same update/change
- [ x] I have run `Set-AVMModule` locally to generate the supporting module files.
- [ x] My corresponding pipelines / checks run clean and green without any errors or warnings

@jongio for notification.

2024-06-10 08:59 UTC, bryansan-msft requested changes
Added comments mostly in code simplification regarding unused parameters

2024-06-10 08:59 UTC, bryansan-msft commented on avm/res/document-db/database-account/tests/e2e/role/dependencies.bicep
> +resource keyVault 'Microsoft.KeyVault/vaults@2021-06-01-preview' = {
This key vault is not used for testing. Can we remove it?

2024-06-10 08:59 UTC, bryansan-msft commented on avm/res/document-db/database-account/tests/e2e/role/dependencies.bicep
> +param managedIdentity bool = !empty(keyVaultName)
Your test always needs a managed identity. Can we remove this parameter and always emit an identityPrincipalId without a condition?

2024-06-10 08:59 UTC, bryansan-msft commented on avm/res/document-db/database-account/tests/e2e/role/main.test.bicep
> +metadata name = 'Deploying with a key vault reference to save secrets'
This metadata value is a copy paste of another test. Can we write a meaningful one?

2024-06-10 08:59 UTC, bryansan-msft commented on avm/res/document-db/database-account/tests/e2e/role/dependencies.bicep
> +param appKind string = 'app,linux'
Can we simplify all of these parameters and just hardcode them in the bicep resource directly? your test is not using them and this is just added extra noise

2024-06-10 08:59 UTC, bryansan-msft commented on avm/res/document-db/database-account/sql-role/sql-role-definitions/main.bicep
> +  'Microsoft.DocumentDB/databaseAccounts/readMetadata'
Can we decide whether these default values are here or in the parent "sql-role/main.bicep" file? These default values are duplicated these two files.

2024-06-10 08:59 UTC, bryansan-msft commented on avm/res/document-db/database-account/sql-role/main.bicep
> +  'Microsoft.DocumentDB/databaseAccounts/readMetadata'
As i mentioned in my other comment. We need to either have defaults value here or in its children files but not in both as those defaults values are duplicated and generated extra noise and confusion

2024-06-13 07:03 UTC, zedy-wj commented
> Added comments mostly in code simplification regarding unused parameters. Can you please link the workflow run with your new role test in green? the link you posted in the PR description is not opening for me

We have updated  the link to the new role test workflow in the description, and also updated the code based on your suggestion, please review. Thanks.

2024-06-19 17:28 UTC, bryansan-msft approved these changes
Looks good to me

2024-06-20 09:16 UTC, merged