Change helmAppName and helmApp
Azure/bicep-registry-modules pull request #212
Opened 2022-12-01 20:46 UTC by aristosvo

## Description

[helm update --install cert-manager jetstack/cert-manager](https://cert-manager.io/docs/installation/helm/#4-install-cert-manager) == helm update --install ${helmAppName} ${helmApp}

## Updating an existing module

- [x] This is a bug fix:
  - [-] Someone has opened a bug report issue, and I have included "Closes #{bug_report_issue_number}" in the PR description.
  - [-] The bug was found by the module author, and no one has opened an issue to report it yet.
- [-] I have run `brm validate` locally to verify the module files.
- [-] I have run deployment tests locally to ensure the module is deployable.
- [-] I have read the [Updating an existing module](../CONTRIBUTING.md#updating-an-existing-module) section in the contributing guide and updated the `version.json` file properly:
  - [-] The PR contains backwards compatible bug fixes, and I have NOT bumped the MAJOR or MINOR version in `version.json`.
  - [-] The PR contains backwards compatible feature updates, and I have bumped the MINOR version in `version.json`.
  - [-] The PR contains breaking changes, and I have bumped the MAJOR version in `version.json`.

2022-12-05 18:29 UTC, dciborow commented
@aristosvo , 

Looks good (and looks like I switched the params by mistake). Minor update to also fix the name in the test.
https://github.com/aristosvo/bicep-registry-modules/pull/1

2022-12-05 18:29 UTC, dciborow requested changes
Please update unit test as well.

2022-12-05 18:46 UTC, aristosvo commented
@dciborow I also included in my own setup an extra output which makes validation of the output possible. Should I add that as well and is there a possibility to check the exitCode in the unit test?

```bicep
output helmOutputs array = [for (app, i) in helmApps: {
  appName: app.helmAppName
  outputs: helmAppInstalls[i].outputs.commandOutput
}]
```

2022-12-21 20:31 UTC, dciborow commented on modules/deployment-scripts/aks-run-helm/main.bicep
> +output helmOutputs array = [for (app, i) in helmApps: {
@description('Helm Command Output Values')

2022-12-21 20:32 UTC, dciborow commented on modules/deployment-scripts/aks-run-helm/main.bicep
> +output helmOutputs array = [for (app, i) in helmApps: {
```suggestion
@description('Helm Command Output Values')
output helmOutputs array = [for (app, i) in helmApps: {
```

2022-12-21 20:32 UTC, dciborow commented on modules/deployment-scripts/aks-run-helm/main.bicep
> +output helmOutputs array = [for (app, i) in helmApps: {
@aristosvo , we are so close. Just need to add this description field to the new output.

2022-12-21 20:33 UTC, dciborow approved these changes

2022-12-21 20:35 UTC, dciborow commented on modules/deployment-scripts/aks-run-helm/main.bicep
> +output helmOutputs array = [for (app, i) in helmApps: {
@shenglol , these changes are all set once all the checks pass. Looks like we will need you to approve as well.

2023-01-10 21:34 UTC, shenglol commented
@aristosvo Could you update one module at a time? Changing multiple modules in one PR is not supported.

2023-01-10 22:08 UTC, aristosvo commented
> @aristosvo Could you update one module at a time? Changing multiple modules in one PR is not supported.

Sure. I’m currently not close to a pc, but I reverted most of the changes from the GH UI. Feel free to fix the new line change if that is really necessary.

2023-02-01 08:37 UTC, Gordonby commented
@aristosvo - One of the PR checks is failing. Can you `brm generate` and push to fix?

2023-02-01 09:30 UTC, aristosvo commented
@Gordonby Sure, I've tried to fix it, but this wasn't a change to what already was there previously :)

2023-03-21 23:58 UTC, shenglol approved these changes

2023-03-21 23:59 UTC, merged