Feat  additional parameters for anf
Azure/bicep-registry-modules pull request #2695
Opened 2024-07-10 16:22 UTC by bobmclane999

## Description
Additional parameters for NetApp - 

- Active Directory encryption, Kerberos, ldapoverTLS
- Volumes - Cool Access, Zones, replication, 
- Backup Policies, Vaults & backups

## Pipeline Reference

| Pipeline |
| -------- |
|  [![avm.res.net-app.net-app-account](https://github.com/bobmclane999/bicep-registry-modules/actions/workflows/avm.res.net-app.net-app-account.yml/badge.svg?branch=feat--additional-parameters-for-ANF)](https://github.com/bobmclane999/bicep-registry-modules/actions/workflows/avm.res.net-app.net-app-account.yml)        |

## Type of Change

- [ ] Update to CI Environment or utilities (Non-module affecting changes)
- [x] Azure Verified Module updates:
  - [ ] Bugfix containing backwards-compatible bug fixes, and I have NOT bumped the MAJOR or MINOR version in `version.json`:
    - [ ] Someone has opened a bug report issue, and I have included "Closes #{bug_report_issue_number}" in the PR description.
    - [ ] The bug was found by the module author, and no one has opened an issue to report it yet.
  - [ ] Feature update backwards compatible feature updates, and I have bumped the MINOR version in `version.json`.
  - [ ] Breaking changes and I have bumped the MAJOR version in `version.json`.
  - [ ] Update to documentation

## Checklist

- [x] I'm sure there are no other open Pull Requests for the same update/change
- [x] I have run `Set-AVMModule` locally to generate the supporting module files.
- [x] My corresponding pipelines / checks run clean and green without any errors or warnings

2024-07-10 16:41 UTC, bobmclane999 commented
@jtracey93 Please do you mind give this PR the once over ? As only 2nd one :)
@fbinotto Please can you review as soon as you can so we can crack on with our File Share Migration ANF deployments :)

Thanks guys!

2024-07-10 16:51 UTC, jtracey93 commented
hey @bobmclane999, i think you ned to pull in and merge and resolve those merge conflicts. https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/addressing-merge-conflicts/resolving-a-merge-conflict-using-the-command-line

Something like:

```
git fetch upstream
git merge upstream main
<RESOLVE CONFLICTS>
git commit
git push

<RE RUN SET-AVMMODULE SCRIPT>
git commit
git push
```

2024-07-10 17:47 UTC, bobmclane999 commented
@jtracey93  - erm.... think I did something wrong .. I fixed the conflicts in github removing the <<< === >>> committed (as struggling with the commands) then done a sync in vscode, reran the AVVMModule and now lots of red... :'-(
![image](https://github.com/Azure/bicep-registry-modules/assets/142896605/0741804f-8a32-444b-a981-a681e35ddce7)
Any ideas on how to fix? Sorry I know you're a busy man and the football is on soon so maybe one for tomorrow ...

2024-07-11 01:35 UTC, fbinotto commented
Take your time @bobmclane999 and @jtracey93 

I still have to merge https://github.com/Azure/bicep-registry-modules/pull/2636 before I consider this PR. And that PR has some of the changes proposed here.

2024-07-11 07:42 UTC, bobmclane999 commented
Hi @fbinotto yeah we had the issues with the resourceId duplication on the WAF aligned tests similar to #2636 so had to make a similar change to get the test working - 
![image](https://github.com/Azure/bicep-registry-modules/assets/142896605/9d698d1e-7c76-455b-b615-c3fbd60dbc8e)

2024-07-12 02:32 UTC, fbinotto commented
> Hi @fbinotto yeah we had the issues with the resourceId duplication on the WAF aligned tests similar to #2636 so had to make a similar change to get the test working - ![image](https://private-user-images.githubusercontent.com/142896605/347725925-9d698d1e-7c76-455b-b615-c3fbd60dbc8e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA2ODUxNjksIm5iZiI6MTcyMDY4NDg2OSwicGF0aCI6Ii8xNDI4OTY2MDUvMzQ3NzI1OTI1LTlkNjk4ZDFlLTdjNzYtNDU1Yi1iNjE1LWMzZmJkNjBkYmM4ZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxMVQwODAxMDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wMGQ1ODlhM2E5YjZmNmRjOTE0YzRmOWNhNTMwYjVmZWEyNDVjZDA1NTZhZTFhNDM2MTI1MGIxMzY5ODY5ZWNiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.gC0gpc9WHOQ02nJCqfWT8C06nf-k-DIFum2X3RaujJ0)
> 
> Sorry to push :( but do you have a timescale on approving the other PR (well and this one :)) as we are mid project for a File Migration using ANF so deadlines are a little tight hence all the changes... tyvm Shaun

It should be merged today or tomorrow, then you should be able to update your PR and I can approve.

2024-07-12 21:52 UTC, jtracey93 commented
Hey @bobmclane999, I see @fbinotto's PR is now merged thanks to @AlexanderSehr's approval 👍 

You can now pull in these changes into your branch and then re-run the test and README generation etc. and then @fbinotto should be good to review and get this one approved and merged too 👍

2024-07-15 02:41 UTC, fbinotto commented
@bobmclane999 please do so before tomorrow night as I will be on leave for a week.

2024-07-15 10:47 UTC, jtracey93 commented
@fbinotto are you happy for me to approve in your absence if needed?

2024-07-15 14:17 UTC, jtracey93 commented
@fbinotto looks like its good for a review, lets see if we can get it in before you go, if not let me know

2024-07-16 02:36 UTC, fbinotto requested changes, later dismissed
LGTM. Just one minor change and we can merge,

2024-07-16 02:36 UTC, fbinotto commented on avm/res/net-app/net-app-account/capacity-pool/main.bicep
> -      zones: volume.?zones
These should not be removed. This syntax automatically pull the default from the referenced volume module.
Remove your lines 97 and 103 and leave these.

2024-07-16 02:37 UTC, fbinotto commented
> @fbinotto are you happy for me to approve in your absence if needed?

Yes, go ahead. I have requested only a minor change.

2024-07-16 07:59 UTC, bobmclane999 commented
@fbinotto / @jtracey93  - have put networkFeatures and Zones params back and previous and submitted the PR again for review... thanks muchly Shaun :)
Have a great week off @fbinotto !

2024-07-16 09:27 UTC, jtracey93 commented
@bobmclane999 did you re-run the `Set-AVMModule` script post making those changes and re run the tests?

2024-07-16 11:04 UTC, bobmclane999 commented
> @bobmclane999 did you re-run the `Set-AVMModule` script post making those changes and re run the tests?

Hi @jtracey93  actually no I didn't let me do and let you know when I've re-submitted tyvm

2024-07-16 14:58 UTC, bobmclane999 commented
Hi @jtracey93  - re-ran a test after another commit (post Set-AVMModule) and have another badge here - 

[![avm.res.net-app.net-app-account](https://github.com/bobmclane999/bicep-registry-modules/actions/workflows/avm.res.net-app.net-app-account.yml/badge.svg?branch=feat--additional-parameters-for-ANF)](https://github.com/bobmclane999/bicep-registry-modules/actions/workflows/avm.res.net-app.net-app-account.yml)

Is this the correct place to put it ?

2024-07-16 16:10 UTC, jtracey93 approved these changes

2024-07-16 16:11 UTC, merged