feat : Add support for Blob service, container to storage account module
Azure/bicep-registry-modules pull request #368
Opened 2023-05-09 14:08 UTC by AshutoshNirkhe

## Description

If you haven't already, read the full [contribution guide](https://github.com/Azure/bicep-registry-modules/blob/main/CONTRIBUTING.md). The guide may have changed since the last time you read it, so please double-check. Once you are done and ready to submit your PR, edit the PR description and run through the relevant checklist below.

Enable GitHub Worksflows in your fork to enable auto-generation of assets with our [GitHub Action](/.github/workflows/push-auto-generate.yml).
To trigger GitHub Actions after auto-generation, [add a GitHub PAT](https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token) as a secret in your forked repository called `PAT`.

## Adding a new module

- [ ] A proposal has been submitted and approved.
- [ ] I have included "Closes #{module_proposal_issue_number}" in the PR description.
- [ ] I have run `brm validate` locally to verify the module files.
- [ ] I have run deployment tests locally to ensure the module is deployable.

## Updating an existing module

- [ ] This is a bug fix:
  - [ ] Someone has opened a bug report issue, and I have included "Closes #{bug_report_issue_number}" in the PR description.
  - [ ] The bug was found by the module author, and no one has opened an issue to report it yet.
- [ ] I have run `brm validate` locally to verify the module files.
- [ ] I have run deployment tests locally to ensure the module is deployable.
- [ ] I have read the [Updating an existing module](https://github.com/Azure/bicep-registry-modules/blob/main/CONTRIBUTING.md#updating-an-existing-module) section in the contributing guide and updated the `version.json` file properly:
  - [ ] The PR contains backwards compatible bug fixes, and I have NOT bumped the MAJOR or MINOR version in `version.json`.
  - [ ] The PR contains backwards compatible feature updates, and I have bumped the MINOR version in `version.json`.
  - [ ] The PR contains breaking changes, and I have bumped the MAJOR version in `version.json`.
- [ ] I have updated the examples in README with the latest module version number.

2023-05-09 14:22 UTC, AshutoshNirkhe commented
@dciborow @shenglol please review the new PR with same contents copied from https://github.com/Azure/bicep-registry-modules/pull/326 as rebase messed it all!

2023-05-12 12:33 UTC, AshutoshNirkhe commented
> @dciborow @shenglol please review the new PR with same contents copied from #326 as rebase messed it all there! cc : @thllxb

@shenglol can you please review/approve and merge if it looks good?

2023-05-12 17:46 UTC, shenglol commented
Could you bump the major version since we are adding new resources to the module?

2023-05-15 11:23 UTC, AshutoshNirkhe commented
> Could you bump the major version since we are adding new resources to the module?

@shenglol bumped the major version now. Please review/approve if good, thanks.

2023-05-16 16:56 UTC, dciborow commented on modules/storage/storage-account/version.json
> +  "version": "2.0",
will need to update the README to point for 2.0.1

2023-05-16 16:57 UTC, dciborow commented on modules/storage/storage-account/version.json
> +  "version": "2.0",
also need to regen, if you set this up, we can take care of it automatically for you.

Enable GitHub Worksflows in your fork to enable auto-generation of assets with our [GitHub Action](https://github.com/.github/workflows/push-auto-generate.yml).
To trigger GitHub Actions after auto-generation, [add a GitHub PAT](https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token) as a secret in your forked repository called PAT.

2023-05-16 17:05 UTC, dciborow commented on modules/storage/storage-account/version.json
> +  "version": "2.0",
@AshutoshNirkhe , i poked the changes directly into your branch since everything else looks good.

2023-05-16 17:10 UTC, dciborow commented on modules/storage/storage-account/main.bicep
> +}
```suggestion
type lastAccessTimeTrackingPolicy = {
  blobType: [
    'string'
  ]
  enable: bool
  name: 'AccessTimeTracking'
  trackingGranularityInDays: trackingGranularityInDays?
}
```

blobType, name, and trackingGranularityInDays are read only. Do we need to include them.

2023-05-16 17:15 UTC, dciborow commented on modules/storage/storage-account/main.bicep
> +type resourceType = string
```suggestion
type roleAssignmentsArray = {
  description: string?
  roleDefinitionIdOrName: string?
  principalIds: string[]?
  principalType: string?
  resourceType: string?
}[]
 
```

2023-05-16 17:16 UTC, dciborow commented on modules/storage/storage-account/main.bicep
> +type resourceType = string
we haven't come up with any style guidelines for custom typing yet... but I don't think there is an advantage to breaking it up further.

2023-05-16 17:21 UTC, dciborow commented on modules/storage/storage-account/main.bicep
> +type resourceType = string
@jeskew , could you give us some feedback on this PR, particularly any suggestions for how to write the custom types? Want to be consistent with people as we review the usage.

2023-05-16 17:22 UTC, dciborow requested changes
The main pieces all look good. Would just like to bring in Jonny to nitpick the usage of custom types.

2023-05-16 17:26 UTC, dciborow commented on modules/storage/storage-account/main.bicep
> +type changeFeedretentionInDays = int
```suggestion
type changeFeed = {
  enabled: bool
  @minValue(1)
  @maxValue(146000)
  retentionInDays: int?
}

```

2023-05-16 17:27 UTC, dciborow commented on modules/storage/storage-account/main.bicep
> +type containerDeleteRetensionPolicyDays = int
```suggestion
type containerDeleteRetentionPolicy = {
  allowPermanentDelete: bool
  @minValue(1)
  @maxValue(365)
  days: int?
  enabled: bool
}

```

2023-05-16 17:28 UTC, dciborow commented on modules/storage/storage-account/main.bicep
> +type restorePolicyDays = int
```suggestion
type restorePolicy = {
  @minValue(1)
  @maxValue(365)
  days: int?
  enabled: bool
}

```

2023-05-16 17:30 UTC, dciborow commented on modules/storage/storage-account/main.bicep
> +}
```suggestion
type blobServiceContainerProperties = {
  defaultEncryptionScope: string?
  denyEncryptionScopeOverride: string?
  immutableStorageWithVersioning: immutableStorageWithVersioning?
  @allowed( [ 'Blob', 'Container', 'None' ])
  publicAccess: string?
}

type immutableStorageWithVersioning = {
  enabled: bool
}
```

2023-05-16 17:35 UTC, dciborow commented on modules/storage/storage-account/main.bicep
> +type resourceType = string
changed my mind... let's complete this now and circle back around if we want to refactor types.

2023-05-16 17:35 UTC, dciborow approved these changes

2023-05-16 17:35 UTC, merged

2023-05-17 05:02 UTC, AshutoshNirkhe commented
> The main pieces all look good. Would just like to bring in Jonny to nitpick the usage of custom types.

thanks a lot @dciborow for review/corrections and merging the PR!