Add connection string output to Event Hub namespace module
Azure/bicep-registry-modules pull request #3906
Opened 2024-12-09 21:26 UTC by dciborow

Fixes #3638

Add output for Event Hub namespace connection string

* Add output for connection string using `listKeys` function in `avm/res/event-hub/namespace/main.bicep`
* Update `outputs` section in `avm/res/event-hub/namespace/main.bicep` to include connection string
* Document new output for connection string in `avm/res/event-hub/namespace/README.md`

---

For more details, open the [Copilot Workspace session](https://copilot-workspace.githubnext.com/Azure/bicep-registry-modules/pull/3906?shareId=07afe390-88ac-4688-89f9-6038b6188816).

2024-12-10 11:34 UTC, elanzel commented
Hi @dciborow , event hub connection string is a sensitive information, publishing it as output is not a best practice. We should instead add to the module the possibility to create a keyvault, when required, and store there the connection string as a secret. Something similar has already been done for the storage account https://github.com/Azure/bicep-registry-modules/tree/main/avm/res/storage/storage-account#Outputs
Can you update the code in that way?

2024-12-10 11:36 UTC, elanzel requested changes

2024-12-10 11:36 UTC, elanzel commented on avm/res/event-hub/namespace/main.bicep
print the connection string as output is not a security best practice, the suggested way is to leverage a keyvault as already done for the storage account module https://github.com/Azure/bicep-registry-modules/tree/main/avm/res/storage/storage-account#parameter-secretsexportconfiguration

2024-12-11 05:29 UTC, rujche commented on avm/res/event-hub/namespace/main.bicep
we can do like like cosmos did: https://github.com/azure-javaee/azure-dev/blob/d1c179a8392341802d0ef686354877b49eb80d24/cli/azd/resources/scaffold/templates/resources.bicept#L104

> ![Image](https://github.com/user-attachments/assets/2d11dadb-3e32-4753-bd33-04d68b84844c)

It's stored in Key Vault, and the key vault id is provided by customer.

2025-01-21 12:03 UTC, elanzel commented on avm/res/event-hub/namespace/main.bicep
Hi @dciborow are you planning to update the code in this PR with the suggestions given above?

2025-01-25 00:06 UTC, weikanglim commented on avm/res/event-hub/namespace/main.bicep
I ran into this as well, submitted #4287 #4288

2025-01-25 20:25 UTC, AlexanderSehr commented on avm/res/event-hub/namespace/main.bicep
Much appreciated @weikanglim

2025-05-13 11:09 UTC, AlexanderSehr commented
The secret export to Key Vaults was added since, and additional exports are added via this PR https://github.com/Azure/bicep-registry-modules/pull/5187

2025-05-13 11:09 UTC, closed without merging