Api gateway waf security
Azure/bicep-registry-modules pull request #3942
Opened 2024-12-17 07:57 UTC by ReneHezser

## Description

Adds WAF Security defaults and UDTs.

#AB38383

## Pipeline Reference

| Pipeline |
| -------- |
|   [![avm.res.api-management.service](https://github.com/ReneHezser/bicep-registry-modules/actions/workflows/avm.res.api-management.service.yml/badge.svg)](https://github.com/ReneHezser/bicep-registry-modules/actions/workflows/avm.res.api-management.service.yml)       |

## Type of Change

- [ ] Update to CI Environment or utilities (Non-module affecting changes)
- [x] Azure Verified Module updates:
  - [ ] Bugfix containing backwards-compatible bug fixes, and I have NOT bumped the MAJOR or MINOR version in `version.json`:
    - [ ] Someone has opened a bug report issue, and I have included "Closes #{bug_report_issue_number}" in the PR description.
    - [ ] The bug was found by the module author, and no one has opened an issue to report it yet.
  - [x] Feature update backwards compatible feature updates, and I have bumped the MINOR version in `version.json`.
  - [ ] Breaking changes and I have bumped the MAJOR version in `version.json`.
  - [x] Update to documentation

## Checklist

- [x] I'm sure there are no other open Pull Requests for the same update/change
- [x] I have run `Set-AVMModule` locally to generate the supporting module files.
- [x] My corresponding pipelines / checks run clean and green without any errors or warnings

2025-01-02 19:22 UTC, AlexanderSehr commented on avm/res/api-management/service/main.bicep
> +      protocols: api.?protocols ?? ['https']
```suggestion
      protocols: api.?protocols
```
Anyways the default of the parameter in the child module. Same is true for the `format` property btw

2025-01-02 23:00 UTC, tony-box commented on avm/res/api-management/service/main.bicep
> +      protocols: api.?protocols ?? ['https']
Agree!

2025-01-02 23:13 UTC, tony-box requested changes
This looks good to me. I think just the one fix suggested by @AlexanderSehr and we're good to go. Thanks!

2025-02-20 16:58 UTC, ReneHezser commented
@tony-box the pipeline is green and we are good to merge. There is one open requested change from you, though. Could you please resolve that one?

2025-02-20 20:38 UTC, tony-box approved these changes

2025-02-20 20:39 UTC, merged