feat: `avm/res/cache/redis-enterprise` - Redis Enterprise and Azure Managed Redis (Preview)
Azure/bicep-registry-modules pull request #4114
Opened 2024-12-30 22:00 UTC by JeffreyCA

## Description

Initial implementation of Bicep AVM for Redis Enterprise and Azure Managed Redis (Preview) caches (`Microsoft.Cache/redisEnterprise`).

There is a related module, `avm/res/cache/redis`, that covers `Microsoft.Cache/redis`:

| Module Name                | Resource Type                  | SKUs                                                                                       |
|----------------------------|--------------------------------|--------------------------------------------------------------------------------------------|
| `avm/res/cache/redis`        | Microsoft.Cache/redis          | **OSS Redis:** Basic, Standard, Premium                                                                   |
| `avm/res/cache/redis-enterprise` (this PR) | Microsoft.Cache/redisEnterprise | **Redis Enterprise:** Enterprise, Enterprise Flash<br>**Azure Managed Redis (Preview):** Balanced, Compute Optimized, Flash Optimized, Memory Optimized |

![image](https://github.com/user-attachments/assets/7128fcea-0708-4ae5-b2ed-8e1e1b9dd6ff)

Closes https://github.com/Azure/Azure-Verified-Modules/issues/1731.

## Pipeline Reference

I'm facing issues setting up CI on my fork using my Azure subscription and Service Principal in the Microsoft tenant, but was able to validate all the E2E tests passed using [`Test-ModuleLocally.ps1`](https://github.com/Azure/bicep-registry-modules/blob/main/utilities/tools/Test-ModuleLocally.ps1).

| Pipeline |
| -------- |
|          |

## Type of Change

- [ ] Update to CI Environment or utilities (Non-module affecting changes)
- [x] Azure Verified Module updates:
  - [ ] Bugfix containing backwards-compatible bug fixes, and I have NOT bumped the MAJOR or MINOR version in `version.json`:
    - [ ] Someone has opened a bug report issue, and I have included "Closes #{bug_report_issue_number}" in the PR description.
    - [ ] The bug was found by the module author, and no one has opened an issue to report it yet.
  - [ ] Feature update backwards compatible feature updates, and I have bumped the MINOR version in `version.json`.
  - [ ] Breaking changes and I have bumped the MAJOR version in `version.json`.
  - [x] Update to documentation

## Checklist

- [x] I'm sure there are no other open Pull Requests for the same update/change
- [x] I have run `Set-AVMModule` locally to generate the supporting module files.
- [ ] My corresponding pipelines / checks run clean and green without any errors or warnings

2025-01-09 20:36 UTC, AlexanderSehr commented on avm/res/cache/redis-enterprise/tests/e2e/kv-secrets/dependencies.bicep
> +    tenantId: subscription().tenantId
```suggestion
    tenantId: subscription().tenantId
    enablePurgeProtection: null
```

Not sure, is `purgeProtection` not enabled by default? If so, we should definitely disable it. The same comment would actually go for the `redis` module update

2025-01-09 20:36 UTC, AlexanderSehr commented on avm/res/cache/redis-enterprise/tests/e2e/kv-secrets/dependencies.bicep
> +@description('The name of the Key Vault created.')
```suggestion
@description('The resource ID of the created Key Vault.')
```

2025-01-09 20:39 UTC, AlexanderSehr commented on avm/res/cache/redis-enterprise/tests/e2e/waf-aligned/main.test.bicep
> +      }
```suggestion
```

2025-01-09 20:39 UTC, AlexanderSehr commented on avm/res/cache/redis-enterprise/tests/e2e/waf-aligned/main.test.bicep
> +      minimumTlsVersion: '1.2'
```suggestion
```
Anyways the default.

2025-01-09 20:48 UTC, AlexanderSehr commented on avm/res/cache/redis-enterprise/tests/e2e/amr/main.test.bicep
> +metadata description = 'This instance deploys an Azure Managed Redis (Preview) cache with the minimum set of required parameters.'
As you call out "preview" - I recall that `redis-enterprise` was already implemented in the CARML days but we had to 'retire' it. We documented it as a ['known issue'[(https://github.com/Azure/ResourceModules/wiki/Known%20issues#cacheredis-enterprise) back then. @jtracey93 would you happen to know if we'd be able to deploy set resource in the AVM subscription? In the CARML one it was definitely not an option.

2025-01-09 20:53 UTC, AlexanderSehr commented on avm/res/cache/redis-enterprise/tests/e2e/amr-entra-id/dependencies.bicep
> +output managedIdentityName string = managedIdentity.name
```suggestion
@description('The resource ID of the created Managed Identity.')
output managedIdentityResourceId string = managedIdentity.id

@description('The client ID of the created Managed Identity.')
output managedIdentityClientId string = managedIdentity.properties.clientId

@description('The principal ID of the created Managed Identity.')
output managedIdentityPrincipalId string = managedIdentity.properties.principalId

@description('The name of the created Managed Identity.')
output managedIdentityName string = managedIdentity.name
```

2025-01-09 20:55 UTC, AlexanderSehr commented on avm/res/cache/redis-enterprise/tests/e2e/active-geo-replication/main.test.bicep
> +var redisName2 = '${namePrefix}${serviceShort}002'
Would be great to move them to the place they're used first (which should be the dependency deployments) and return the values from there to reference in the test. I'm aware this is a lot more complicated than simply having them as variables/parameters, but consistency-wise it's quite helpful to follow a consistent pattern of where values are defined etc. Happy to discuss though if you really don't like that 😄

2025-01-09 20:56 UTC, AlexanderSehr commented on avm/res/cache/redis-enterprise/tests/e2e/active-geo-replication/main.test.bicep
> +var redisName2 = '${namePrefix}${serviceShort}002'
The `zones` specification can probably be removed in its entirety as you defined it as a default value in the dependency deployment which should do the trick.

2025-01-09 20:57 UTC, AlexanderSehr commented on avm/res/cache/redis-enterprise/tests/e2e/active-geo-replication/main.test.bicep
> +module nestedDependencies1 'dependencies1.bicep' = {
Needed if not used?

2025-01-09 21:03 UTC, AlexanderSehr commented on avm/res/cache/redis-enterprise/tests/e2e/active-geo-replication/dependencies2.bicep
> +module redis '../../../main.bicep' = {
Should not use itself during a test as a change in the module could have quite unexpected effects. Instead we highly recommend to either use a plain `resource` deployment, or a version version of the module (which is not an option here). Also makes it easier for somebody that wants to perform a similar deployment (i.e., with geo-replication) to understand what dependencies are required.

So in this case something along the lines of
```bicep
resource redisCluster 'Microsoft.Cache/redisEnterprise@2024-09-01-preview' = {
  name: name
  location: location
  properties: {
    minimumTlsVersion: '1.2'
  }
  sku: {
    capacity: 2
    name: 'Enterprise_E5'
  }
  zones: [
    '1'
    '2'
    '3'
  ]'

  resource redisDatabase 'databases@2024-09-01-preview' = {
     (...)
  {
}
```

2025-01-09 21:05 UTC, AlexanderSehr commented on avm/res/cache/redis-enterprise/main.bicep
> +}
Missing `@description('(...)')` for the properties

2025-01-09 21:07 UTC, AlexanderSehr commented on avm/res/cache/redis-enterprise/main.bicep
> +resource redisDatabase 'Microsoft.Cache/redisEnterprise/databases@2024-09-01-preview' = {
Should be a nested child module like [here](https://github.com/Azure/ResourceModules/blob/v0.11.1/modules/cache/redis-enterprise/database/main.bicep).
The same goes for the `accessPplicyAssignments` which in turn should be a child of the database module as per the resource type tree.
This will enable us to publish the same as individual modules in the future and anyways align with the specs.

2025-01-09 21:10 UTC, AlexanderSehr commented on avm/res/cache/redis-enterprise/main.bicep
> +resource redisDatabase 'Microsoft.Cache/redisEnterprise/databases@2024-09-01-preview' = {
This, in turn, means this PR #3811 should not have been merged.

2025-01-09 21:17 UTC, AlexanderSehr requested changes
Create work @JeffreyCA, not much to call out :) Let me know if you have any questions regarding the comments.
If you addressed any please just comment them as such and I'll resolve them after a re-review.

Also, if you need help with the CI, let me know.

2025-01-09 23:55 UTC, JeffreyCA commented on avm/res/cache/redis-enterprise/main.bicep
> +resource redisDatabase 'Microsoft.Cache/redisEnterprise/databases@2024-09-01-preview' = {
Thanks, so after adding a `redis-enterprise/database/main.bicep` with all the database-level params, how should I handle them from `redis-enterprise/main.bicep`?

I've seen modules take different approaches:

1. Introduce a new `databaseType` in `redis-enterprise/main.bicep` and replace individual database params with a single param of type `databaseType`.

    Example:
    https://github.com/Azure/bicep-registry-modules/blob/5ed0e20a697f2d7ca85da3e4b00e0b864af1dbbb/avm/res/document-db/database-account/main.bicep#L871-L879

2. Replace individual database params in `redis-enterprise/main.bicep` with single database param of type `object`.
3. Go with a "flattened" structure where database params are defined as individual params in `redis-enterprise/main.bicep`.

What is the recommended approach? With 1 and 3, it looks like there will be some duplication of the child module params and descriptions since they're redefined in the child's `main.bicep`?

2025-01-10 00:03 UTC, JeffreyCA commented on avm/res/cache/redis-enterprise/tests/e2e/kv-secrets/dependencies.bicep
> +    tenantId: subscription().tenantId
It's disabled by default.

![image](https://github.com/user-attachments/assets/031342e9-c587-4792-862e-792ccc9ac0c7)

2025-01-10 15:07 UTC, AlexanderSehr commented on avm/res/cache/redis-enterprise/main.bicep
> +resource redisDatabase 'Microsoft.Cache/redisEnterprise/databases@2024-09-01-preview' = {
We have a (imho) relatively solid pattern implemented in some (but not all modules). One example I recently implemented (but is sitting in a PR) can be found [here](https://github.com/Azure/bicep-registry-modules/blob/9c16eced981923826871327291d98a40a3f3bdbd/avm/res/net-app/net-app-account/main.bicep#L383-L403).

In essence, the recommendation is to apply the following steps
- Break down the template into the folder path
- Then, start with the leaf template (in your case `accessPolicyAssignments`) and implement it like its is own module, with an `existing` reference to its parent module(s) who's name(s) you pass through. The module should have a parameter for at least every property in the `properties` block of the resource type. If any of them are arrays/objects they ideally have a UDT to describe them. Each UDT for any such parameter should have an `@export()` annotation (and optionally a description).
- Then you go one level up and again implement the resource (in your case database) as its own module and apply all the steps from the previous bullet. Now here's the 'special' addition. As each database can have `accessPolicyAssignments` you should have a parameter `param accessPolicyAssignments accessPolicyAssignmentType[]?` which allows users to specify the same. This `accessPolicyAssignmentType` should be implemented in the current module and specify the same parameters as the child resource its pointing to. If that child contained any UDTs of its own, you should import and reuse them. Last but not least, the child should be deployable through its parent (i.e., you should have a module deployment for the `accessPolicyAssignments` like `module accessPolicyAssignments 'accessPolicyAssignment/main.bicep' = [ for (accessPolicyAssignment, index) in (accessPolicyAssignments ?? []): { (...) }`. Yes you'd have to specify the child-modules top-level parameter again in the type, but only once and without a value.
- Last but not least, going up one last level to the `redis-enterprise` module you now apply the same steps of the previous bullet but you don't have to care about the types of the `accessPolicyAssignment` module. Instead you have a type for the `database` which simply imports the `accessPolicyAssignmentType` and any content of the type is already taken care of by the child.

The same logic essentially applies to an entire tree of a module. You always have to specify parameters twice, as a parameter and in a type in the parent (if any), but no more than that.

The Net-App branch I linked above should give you a good idea, but beware there's a lot more stuff in there (like other existing resource references etc.) so try to not get distracted 😄 

If what I wrote above does not make sense (it's not easy to describe without 'showing') let me know and jump on a quick call. It is in fact quite straight-forward approach, once you've done it once.

2025-01-11 00:22 UTC, JeffreyCA commented on avm/res/cache/redis-enterprise/tests/e2e/kv-secrets/dependencies.bicep
> +@description('The name of the Key Vault created.')
Updated

2025-01-11 00:22 UTC, JeffreyCA commented on avm/res/cache/redis-enterprise/tests/e2e/waf-aligned/main.test.bicep
> +      }
Removed

2025-01-11 00:22 UTC, JeffreyCA commented on avm/res/cache/redis-enterprise/tests/e2e/waf-aligned/main.test.bicep
> +      minimumTlsVersion: '1.2'
Updated

2025-01-11 00:22 UTC, JeffreyCA commented on avm/res/cache/redis-enterprise/tests/e2e/active-geo-replication/main.test.bicep
> +var redisName2 = '${namePrefix}${serviceShort}002'
Sure, can you take another look?

2025-01-11 00:23 UTC, JeffreyCA commented on avm/res/cache/redis-enterprise/tests/e2e/active-geo-replication/main.test.bicep
> +module nestedDependencies1 'dependencies1.bicep' = {
Updated to a single dependency

2025-01-11 00:23 UTC, JeffreyCA commented on avm/res/cache/redis-enterprise/tests/e2e/active-geo-replication/dependencies2.bicep
> +module redis '../../../main.bicep' = {
Thanks, updated

2025-01-11 00:23 UTC, JeffreyCA commented on avm/res/cache/redis-enterprise/main.bicep
> +}
Added

2025-01-11 00:24 UTC, JeffreyCA commented on avm/res/cache/redis-enterprise/main.bicep
> +resource redisDatabase 'Microsoft.Cache/redisEnterprise/databases@2024-09-01-preview' = {
Thanks for clarifying, that helped a lot. Can you take another look when you get a chance?

2025-01-11 08:49 UTC, AlexanderSehr commented on avm/res/cache/redis-enterprise/database/access-policy-assignment/main.bicep
> +param objectId string
May make sense to rename to `userObjectId` to be more description. What do you think?

2025-01-11 09:02 UTC, AlexanderSehr commented on avm/res/cache/redis-enterprise/tests/e2e/active-geo-replication/dependencies.bicep
> +param serviceShort string = 'creagr'
Should be replaced with `redisClusterName` and the `serviceShort` only be specified in the `main.test.bicep`. 

The idea: All names of resources that 'could' conflict with one another (usually top-level resources) should be generated in the `main.test.bicep` and be passed down to where they are needed. All other names / properties should be defined directly where they are used.

The main reason for this design decision is that it makes it quite easy to understand 1. what resources are deployed and 2. (when troubleshooting) which resource name of the error message links to which resource (as they're all visible in one place).

2025-01-11 09:07 UTC, AlexanderSehr commented on avm/res/cache/redis-enterprise/tests/e2e/active-geo-replication/main.test.bicep
> +param geoReplicationGroupName string = 'geo-replication-group'
A last property that should be moved to the `dependencies.bicep` as it's not passed in by the CI. As far as I'm concerned, it coult potentially even be specified directly where it is used and then returned by the `dependencies.bicep` file like `output geoReplicationResourceGroupName string = redisCluster::redisDatabase.properties.geoReplication.groupNickname` and be referenced as such.

2025-01-11 09:08 UTC, AlexanderSehr commented on avm/res/cache/redis-enterprise/tests/e2e/amr-entra-id/dependencies.bicep
> +output managedIdentityName string = managedIdentity.name
```suggestion
@description('The principal ID of the created Managed Identity.')
output managedIdentityPrincipalId string = managedIdentity.properties.principalId
```

Only this one seems to be used.

2025-01-11 09:12 UTC, AlexanderSehr commented on avm/res/cache/redis-enterprise/main.bicep
> +  name: '${uniqueString(deployment().name, location)}-redis-database'
I just gotta ask - can a Redis-Enterprise instance only have a single database?

2025-01-11 09:13 UTC, AlexanderSehr commented on avm/res/cache/redis-enterprise/tests/e2e/active-geo-replication/main.test.bicep
> +var redisName2 = '${namePrefix}${serviceShort}002'
Just did and added one last comment. Great work @JeffreyCA, will resolve.

2025-01-11 09:13 UTC, AlexanderSehr commented on avm/res/cache/redis-enterprise/tests/e2e/active-geo-replication/dependencies2.bicep
> +module redis '../../../main.bicep' = {
Much appreciated, thanks. Resolving...

2025-01-11 09:13 UTC, AlexanderSehr commented on avm/res/cache/redis-enterprise/main.bicep
> +}
Great, thanks. Resolving...

2025-01-13 17:50 UTC, JeffreyCA commented on avm/res/cache/redis-enterprise/main.bicep
> +  name: '${uniqueString(deployment().name, location)}-redis-database'
Yes correct

2025-01-13 17:50 UTC, JeffreyCA commented on avm/res/cache/redis-enterprise/tests/e2e/amr-entra-id/dependencies.bicep
> +output managedIdentityName string = managedIdentity.name
Thanks, updated

2025-01-13 17:51 UTC, JeffreyCA commented on avm/res/cache/redis-enterprise/tests/e2e/active-geo-replication/main.test.bicep
> +param geoReplicationGroupName string = 'geo-replication-group'
Updated

2025-01-13 17:52 UTC, JeffreyCA commented on avm/res/cache/redis-enterprise/tests/e2e/active-geo-replication/dependencies.bicep
> +param serviceShort string = 'creagr'
Got it, could you please take another look at the latest changes?

2025-01-13 17:52 UTC, JeffreyCA commented on avm/res/cache/redis-enterprise/database/access-policy-assignment/main.bicep
> +param objectId string
Sure, I renamed it

2025-01-15 15:13 UTC, AlexanderSehr commented on avm/res/cache/redis-enterprise/tests/e2e/active-geo-replication/dependencies.bicep
> +param serviceShort string = 'creagr'
It looks like a dream come true @JeffreyCA 💪

2025-01-15 15:13 UTC, AlexanderSehr commented on avm/res/cache/redis-enterprise/tests/e2e/amr/main.test.bicep
> +metadata description = 'This instance deploys an Azure Managed Redis (Preview) cache with the minimum set of required parameters.'
Sidenote: Added it to our agenda for tomorrow

2025-01-15 15:14 UTC, AlexanderSehr commented on avm/res/cache/redis-enterprise/main.bicep
> +  name: '${uniqueString(deployment().name, location)}-redis-database'
Interesting. Thanks for clarifying sir

2025-01-23 16:46 UTC, AlexanderSehr commented
> Following up on this @AlexanderSehr, what are the next steps for getting this in?

Hey @JeffreyCA,
we didn't get to it last week but briefly touched on it today. I'll try to test deploy the resource into the AVM subscription to see if we can actually be tested. If not we have to agree on a plan B as this would render the module untestable for us (which may or may not be a blocker). But we'll cross that bridge when we get there.
I'll try to run the test deployment this week but please don't quote me on that as I'm streched very thin.

2025-02-15 12:56 UTC, AlexanderSehr commented on avm/res/cache/redis-enterprise/tests/e2e/amr/main.test.bicep
> +metadata name = 'Azure Managed Redis (Preview)'
Please add the role assignment tests we have in other modules here as well, given that the module does offer the feature.

2025-02-18 20:01 UTC, AlexanderSehr commented on avm/res/cache/redis-enterprise/database/access-policy-assignment/main.bicep
> +metadata owner = 'Azure/module-maintainers'
```suggestion
```

2025-02-18 20:02 UTC, AlexanderSehr commented on avm/res/cache/redis-enterprise/database/access-policy-assignment/main.bicep
> +metadata owner = 'Azure/module-maintainers'
Change requires ARM template to be rebuild

2025-02-18 20:02 UTC, AlexanderSehr commented on avm/res/cache/redis-enterprise/database/main.bicep
> +metadata owner = 'Azure/module-maintainers'
```suggestion
```
Change requires ARM template to be rebuild

2025-02-18 20:03 UTC, AlexanderSehr commented on avm/res/cache/redis-enterprise/database/main.bicep
> +    split((secretsExportConfiguration.?keyVaultResourceId ?? '////'), '/')[4]
```suggestion
    split(secretsExportConfiguration.?keyVaultResourceId!, '/')[2],
    split(secretsExportConfiguration.?keyVaultResourceId!, '/')[4]
```
A recent update to the language allows us to simplify this

2025-02-18 20:03 UTC, AlexanderSehr commented on avm/res/cache/redis-enterprise/database/main.bicep
> +    split((secretsExportConfiguration.?keyVaultResourceId ?? '////'), '/')[4]
Change requires ARM template to be rebuild

2025-02-18 20:06 UTC, AlexanderSehr commented on avm/res/cache/redis-enterprise/main.bicep
> +    split((customerManagedKey.?keyVaultResourceId ?? '////'), '/')[4]
```suggestion
  name: last(split(customerManagedKey.?keyVaultResourceId!, '/'))
  scope: resourceGroup(
    split(customerManagedKey.?keyVaultResourceId!, '/')[2],
    split(customerManagedKey.?keyVaultResourceId!, '/')[4]
```

2025-02-18 20:07 UTC, AlexanderSehr commented on avm/res/cache/redis-enterprise/main.bicep
> +    name: customerManagedKey.?keyName ?? 'dummyKey'
```suggestion
    name: customerManagedKey.?keyName!
```

2025-02-18 20:07 UTC, AlexanderSehr commented on avm/res/cache/redis-enterprise/main.bicep
> +    split((customerManagedKey.?userAssignedIdentityResourceId ?? '////'), '/')[4]
```suggestion
  name: last(split(customerManagedKey.?userAssignedIdentityResourceId, '/'))
  scope: resourceGroup(
    split(customerManagedKey.?userAssignedIdentityResourceId!, '/')[2],
    split(customerManagedKey.?userAssignedIdentityResourceId!, '/')[4]
```

2025-02-18 20:10 UTC, AlexanderSehr commented on avm/res/cache/redis-enterprise/main.bicep
> +        )
```suggestion
    scope: resourceGroup(
      split(privateEndpoint.?resourceGroupResourceId ?? resourceGroup().id, '/')[2],
      split(privateEndpoint.?resourceGroupResourceId ?? resourceGroup().id, '/')[4]
    )

```

2025-02-18 20:12 UTC, AlexanderSehr commented on avm/res/cache/redis-enterprise/tests/e2e/max/main.test.bicep
> +      highAvailability: 'Disabled'
Please add the role assignment tests we have in other modules here as well, given that the module does offer the feature.

```suggestion
      highAvailability: 'Disabled'
      roleAssignments: [
        {
          name: 'd7aa3dfa-6ba6-4ed8-b561-2164fbb1327e'
          roleDefinitionIdOrName: 'Owner'
          principalId: nestedDependencies.outputs.managedIdentityPrincipalId
          principalType: 'ServicePrincipal'
        }
        {
          name: guid('Custom seed ${namePrefix}${serviceShort}')
          roleDefinitionIdOrName: 'b24988ac-6180-42a0-ab88-20f7382dd24c'
          principalId: nestedDependencies.outputs.managedIdentityPrincipalId
          principalType: 'ServicePrincipal'
        }
        {
          roleDefinitionIdOrName: subscriptionResourceId(
            'Microsoft.Authorization/roleDefinitions',
            'acdd72a7-3385-48ef-bd42-f606fba81ae7'
          )
          principalId: nestedDependencies.outputs.managedIdentityPrincipalId
          principalType: 'ServicePrincipal'
        }
      ]
```

2025-02-18 20:13 UTC, AlexanderSehr commented on avm/res/cache/redis-enterprise/tests/e2e/waf-aligned/main.test.bicep
> +      location: resourceLocation
```suggestion
```

2025-02-18 20:13 UTC, AlexanderSehr commented on avm/res/cache/redis-enterprise/tests/e2e/kv-secrets/main.test.bicep
> +    location: resourceLocation
```suggestion
```

2025-02-18 20:13 UTC, AlexanderSehr commented on avm/res/cache/redis-enterprise/tests/e2e/amr/main.test.bicep
> +      location: enforcedLocation
```suggestion
```

2025-02-18 20:14 UTC, AlexanderSehr commented on avm/res/cache/redis-enterprise/tests/e2e/defaults/main.test.bicep
> +      location: resourceLocation
```suggestion
```

2025-02-18 20:15 UTC, AlexanderSehr commented on avm/res/cache/redis-enterprise/tests/e2e/defaults/main.test.bicep
> +      name: '${namePrefix}${serviceShort}001'
I guess for this one we also need to set a specific sku to work?

2025-02-19 01:36 UTC, JeffreyCA commented on avm/res/cache/redis-enterprise/tests/e2e/defaults/main.test.bicep
> +      name: '${namePrefix}${serviceShort}001'
Yes, updated

2025-02-19 01:38 UTC, JeffreyCA commented on avm/res/cache/redis-enterprise/database/main.bicep
> +    split((secretsExportConfiguration.?keyVaultResourceId ?? '////'), '/')[4]
Thanks

2025-02-19 17:50 UTC, AlexanderSehr approved these changes

2025-02-19 17:50 UTC, merged