Users/alsehr/kube extension
Azure/bicep-registry-modules pull request #547
Opened 2023-10-07 21:03 UTC by AlexanderSehr

## Description

- Migrated kube-extension module to AVM (this will lead to a release `0.1.0`)
- Updated kube-flux metadata as per original readme (note: this will lead to a release `0.1.1`)

| Pipeline |
| - |
| [![avm.res.kubernetes-configuration.extension](https://github.com/AlexanderSehr/bicep-registry-modules/actions/workflows/avm.res.kubernetes-configuration.extension.yml/badge.svg?branch=users%2Falsehr%2Fkube-extension)](https://github.com/AlexanderSehr/bicep-registry-modules/actions/workflows/avm.res.kubernetes-configuration.extension.yml) |
| [![avm.res.kubernetes-configuration.flux-configuration](https://github.com/AlexanderSehr/bicep-registry-modules/actions/workflows/avm.res.kubernetes-configuration.flux-configuration.yml/badge.svg?branch=users%2Falsehr%2Fkube-extension)](https://github.com/AlexanderSehr/bicep-registry-modules/actions/workflows/avm.res.kubernetes-configuration.flux-configuration.yml) |

2023-10-10 06:53 UTC, eriqua requested changes
I'd suggest two separate PRs, one for each module.
Probably a good practice in general, but in particular in this case, since `extension` is dependent on `flux-config`. We should first bump `flux config` and then directly reference the latest 0.1.1 from `extension`.

2023-10-10 07:18 UTC, AlexanderSehr commented
> I'd suggest two separate PRs, one for each module. Probably a good practice in general, but in particular in this case, since `extension` is dependent on `flux-config`. We should first bump `flux config` and then directly reference the latest 0.1.1 from `extension`.

Note taken and will do. Just for background: The reason I opted against it was that it is only a readme update at the end of the day (so there is not even a patch change for the functionality). However, a separate PR won't hurt

2023-10-11 09:40 UTC, eriqua commented on avm/res/kubernetes-configuration/extension/main.bicep
> +module fluxConfiguration 'br/public:avm-res-kubernetesconfiguration-fluxconfiguration:0.1.0' = [for (fluxConfiguration, index) in (fluxConfigurations ?? []): {
```suggestion
module fluxConfiguration 'br/public:avm-res-kubernetesconfiguration-fluxconfiguration:0.1.1' = [for (fluxConfiguration, index) in (fluxConfigurations ?? []): {
```

2023-10-13 15:48 UTC, ChrisSidebotham reviewed
🆗

2023-10-15 18:16 UTC, eriqua commented on avm/res/kubernetes-configuration/extension/tests/e2e/defaults/main.test.bicep
> +
```suggestion

metadata name = 'Using only defaults'
metadata description = '''
This instance deploys the module with the minimum set of required parameters.
> **Note:** The test currently implements additional non-required parameters to cater for a test-specific limitation.
'''
```

2023-10-15 18:17 UTC, eriqua commented on avm/res/kubernetes-configuration/extension/tests/e2e/max/main.test.bicep
> +
```suggestion

metadata name = 'Using large parameter set'
metadata description = 'This instance deploys the module with most of its features enabled.'

```

2023-10-15 18:17 UTC, eriqua commented on avm/res/kubernetes-configuration/extension/tests/e2e/waf-aligned/main.test.bicep
> +
metadata name = 'WAF-aligned'
metadata description = 'This instance deploys the module in alignment with the best-pratices of the Azure Well-Architected Framework.'

2023-10-15 18:17 UTC, eriqua commented on avm/res/kubernetes-configuration/extension/tests/e2e/waf-aligned/main.test.bicep
> +
```suggestion

metadata name = 'WAF-aligned'
metadata description = 'This instance deploys the module in alignment with the best-pratices of the Azure Well-Architected Framework.'

```

2023-10-17 00:44 UTC, eriqua approved these changes
:ok:

2023-10-17 00:44 UTC, merged