feat: Added module virtual-network
Azure/bicep-registry-modules pull request #595
Opened 2023-10-31 12:00 UTC by elbatane

## Description

Added module virtual-network - converted from CARML.

If you haven't already, read the full [contribution guide](https://github.com/Azure/bicep-registry-modules/blob/main/CONTRIBUTING.md). The guide may have changed since the last time you read it, so please double-check. Once you are done and ready to submit your PR, edit the PR description and run through the relevant checklist below.

Enable GitHub Worksflows in your fork to enable auto-generation of assets with our [GitHub Action](/.github/workflows/push-auto-generate.yml).
To trigger GitHub Actions after auto-generation, [add a GitHub PAT](https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token) as a secret in your forked repository called `PAT`.

## Adding a new module

- [ ] A proposal has been submitted and approved.
- [ ] I have included "Closes #{module_proposal_issue_number}" in the PR description.
- [ ] I have run `brm validate` locally to verify the module files.
- [ ] I have run deployment tests locally to ensure the module is deployable.

## Updating an existing module

- [ ] This is a bug fix:
  - [ ] Someone has opened a bug report issue, and I have included "Closes #{bug_report_issue_number}" in the PR description.
  - [ ] The bug was found by the module author, and no one has opened an issue to report it yet.
- [ ] I have run `brm validate` locally to verify the module files.
- [ ] I have run deployment tests locally to ensure the module is deployable.
- [ ] I have read the [Updating an existing module](https://github.com/Azure/bicep-registry-modules/blob/main/CONTRIBUTING.md#updating-an-existing-module) section in the contributing guide and updated the `version.json` file properly:
  - [ ] The PR contains backwards compatible bug fixes, and I have NOT bumped the MAJOR or MINOR version in `version.json`.
  - [ ] The PR contains backwards compatible feature updates, and I have bumped the MINOR version in `version.json`.
  - [ ] The PR contains breaking changes, and I have bumped the MAJOR version in `version.json`.
- [ ] I have updated the examples in README with the latest module version number.

2023-10-31 21:20 UTC, AlexanderSehr commented on avm/res/network/virtual-network/tests/e2e/vnetPeering/main.test.bicep
> +
```suggestion

metadata name = 'Deploying a bi-directional peering'
metadata description = 'This instance deploys the module with both an inbound and outbound peering.'

```

2023-10-31 21:21 UTC, AlexanderSehr commented on avm/res/network/virtual-network/tests/e2e/vnetPeering/main.test.bicep
> +
> **Note:** This requires a regeneration of the top-level readme

2023-10-31 21:24 UTC, AlexanderSehr commented on avm/res/network/virtual-network/tests/e2e/waf-aligned/main.test.bicep
> +metadata description = 'This instance deploys the module with most of its features enabled.'
```suggestion
metadata name = 'WAF-aligned'
metadata description = 'This instance deploys the module in alignment with the best-practices of the Well-Architected Framework.'
```

2023-10-31 21:25 UTC, AlexanderSehr commented on avm/res/network/virtual-network/tests/e2e/waf-aligned/main.test.bicep
> +metadata description = 'This instance deploys the module with most of its features enabled.'
> **Note:** This requires the top-level readme to be regenerated

2023-10-31 21:26 UTC, AlexanderSehr commented on avm/res/network/virtual-network/tests/e2e/waf-aligned/main.test.bicep
> +    ]
```suggestion
```

Not required for WAF-alignment. 
> **Note:** This requires the top-level readme to be regenerated

2023-10-31 21:29 UTC, AlexanderSehr commented on avm/res/network/virtual-network/subnet/main.bicep
> +param networkSecurityGroupId string = ''
```suggestion
param networkSecurityGroupResourceId string = ''
```

2023-10-31 21:29 UTC, AlexanderSehr commented on avm/res/network/virtual-network/subnet/main.bicep
> +param routeTableId string = ''
```suggestion
param routeTableResourceId string = ''
```

2023-10-31 21:29 UTC, AlexanderSehr commented on avm/res/network/virtual-network/subnet/main.bicep
> +param natGatewayId string = ''
```suggestion
param natGatewayResourceId string = ''
```

2023-10-31 21:31 UTC, AlexanderSehr commented on avm/res/network/virtual-network/subnet/main.bicep
> +    } : null
```suggestion
    networkSecurityGroup: !empty(networkSecurityGroupResourceId) ? {
      id: networkSecurityGroupResourceId
    } : null
    routeTable: !empty(routeTableResourceId) ? {
      id: routeTableResourceId
    } : null
    natGateway: !empty(natGatewayResourceId) ? {
      id: natGatewayResourceId
    } : null
```

2023-10-31 21:32 UTC, AlexanderSehr commented on avm/res/network/virtual-network/subnet/main.bicep
> +// =============== //
```suggestion

// =============== //
```

2023-10-31 21:36 UTC, AlexanderSehr commented on avm/res/network/virtual-network/main.bicep
> +param tags object = {}
```suggestion
param tags object?
```

2023-10-31 21:37 UTC, AlexanderSehr commented on avm/res/network/virtual-network/main.bicep
> +param ddosProtectionPlanId string = ''
```suggestion
param ddosProtectionPlanResourceId string = ''
```

2023-10-31 21:37 UTC, AlexanderSehr commented on avm/res/network/virtual-network/main.bicep
> +param ddosProtectionPlanId string = ''
Also please update the other references of this parameter

2023-11-09 22:52 UTC, AlexanderSehr commented on avm/res/network/virtual-network/main.bicep
> +  principalType: ('ServicePrincipal' | 'Group' | 'User' | 'ForeignGroup' | 'Device' | null)?
```suggestion
  principalType: ('ServicePrincipal' | 'Group' | 'User' | 'ForeignGroup' | 'Device')?
```

2023-11-09 22:52 UTC, AlexanderSehr commented on avm/res/network/virtual-network/main.bicep
> +  logAnalyticsDestinationType: ('Dedicated' | 'AzureDiagnostics' | null)?
```suggestion
  logAnalyticsDestinationType: ('Dedicated' | 'AzureDiagnostics')?
```

2023-11-09 22:53 UTC, AlexanderSehr commented on avm/res/network/virtual-network/subnet/main.bicep
> +  principalType: ('ServicePrincipal' | 'Group' | 'User' | 'ForeignGroup' | 'Device' | null)?
```suggestion
  principalType: ('ServicePrincipal' | 'Group' | 'User' | 'ForeignGroup' | 'Device')?
```

2023-11-09 22:53 UTC, AlexanderSehr requested changes
Please fetch latest upstream and regenerate templates & readme's using the `Set-AVMModule` script :)

2023-11-24 15:47 UTC, skydiver1980 approved these changes

2023-11-27 16:47 UTC, AlexanderSehr commented on avm/res/network/virtual-network/tests/e2e/defaults/main.test.bicep
> +    roleAssignments: []
```suggestion
```

This was finally fixed recently :) Hence we can remove it again - but need to refresh the readme

2023-11-27 17:36 UTC, AlexanderSehr approved these changes

2023-11-27 17:37 UTC, merged