new feat: Added routeType type
Azure/bicep-registry-modules pull request #677
Opened 2023-11-28 15:04 UTC by johnlokerse

## Description

Added a new user-defined type called `routeType`.

## Updating an existing module

- [ ] This is a bug fix:
  - [ ] Someone has opened a bug report issue, and I have included "Closes #{bug_report_issue_number}" in the PR description.
  - [ ] The bug was found by the module author, and no one has opened an issue to report it yet.
- [ ] I have run `brm validate` locally to verify the module files.
- [ ] I have run deployment tests locally to ensure the module is deployable.
- [x] I have read the [Updating an existing module](https://github.com/Azure/bicep-registry-modules/blob/main/CONTRIBUTING.md#updating-an-existing-module) section in the contributing guide and updated the `version.json` file properly:
  - [ ] The PR contains backwards compatible bug fixes, and I have NOT bumped the MAJOR or MINOR version in `version.json`.
  - [x] The PR contains backwards compatible feature updates, and I have bumped the MINOR version in `version.json`.
  - [ ] The PR contains breaking changes, and I have bumped the MAJOR version in `version.json`.
- [x] I have updated the examples in README with the latest module version number.

2023-11-28 18:49 UTC, AlexanderSehr commented on avm/res/network/route-table/main.bicep
> +  @description('Name of the route.')
```suggestion
  @description('Required. Name of the route.')
```

2023-11-28 18:49 UTC, AlexanderSehr commented on avm/res/network/route-table/main.bicep
> +    @description('The type of Azure hop the packet should be sent to.')
```suggestion
    @description('Required. The type of Azure hop the packet should be sent to.')
```

2023-11-28 18:50 UTC, AlexanderSehr requested changes
Love it, please not that the requested changes will require a re-run of the `Set-AVMModule` script

2023-11-29 07:52 UTC, johnlokerse commented on avm/res/network/route-table/main.bicep
> +  @description('Name of the route.')
Resolved!

2023-11-29 07:54 UTC, johnlokerse commented
@AlexanderSehr Do you want me to test the change using a deployment?

2023-11-29 08:04 UTC, AlexanderSehr commented
> @AlexanderSehr Do you want me to test the change using a deployment?

Hey @johnlokerse, in general, for any module changes, that would be much appreciated, yes :)

2023-11-30 10:20 UTC, AlexanderSehr commented
Small trick @johnlokerse  ;) 
![image](https://github.com/Azure/bicep-registry-modules/assets/5365358/a23657dd-cda6-4906-93fe-f90ee2727219)

Can be found in your pipeline via the 3 small `...` on the top right

2023-11-30 10:34 UTC, johnlokerse commented
> Small trick @johnlokerse ;) ![image](https://private-user-images.githubusercontent.com/5365358/286896362-a23657dd-cda6-4906-93fe-f90ee2727219.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEzNDA3NDgsIm5iZiI6MTcwMTM0MDQ0OCwicGF0aCI6Ii81MzY1MzU4LzI4Njg5NjM2Mi1hMjM2NTdkZC1jZGE2LTQ5MDYtOTNmZS1mOTBlZTI3MjcyMTkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTEzMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzExMzBUMTAzNDA4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZjVhNTM4NjkwNmI3ZDMxZTU5YmRmZDlmY2M5OTVlMjk2OWUzNzhkNTUxMmVlY2U5OWE2ZjRmN2M5ZGFmN2ZiNiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.WAtTlUCReMeESH5BQaU6Zst8OZh6eCjvZBEAKDI0F40)
> 
> Can be found in your pipeline via the 3 small `...` on the top right.
> 
> Adding it to your PR description.

That's great! Will do that the next time. Thanks for sharing :)

2023-11-30 23:55 UTC, segraef approved these changes
Thank you very much for your contribution @johnlokerse!

2023-12-01 06:38 UTC, AlexanderSehr approved these changes

2023-12-01 06:39 UTC, merged