feat: new module network/nat-gateway
Azure/bicep-registry-modules pull request #744
Opened 2023-12-21 17:20 UTC by fabmas

## Description

New network/nat-gateway module migrated from CARML to AVM

[![avm.res.network.nat-gateways](https://github.com/fabmas/bicep-registry-modules/actions/workflows/avm.res.network.nat-gateway.yml/badge.svg)](https://github.com/fabmas/bicep-registry-modules/actions/workflows/avm.res.network.nat-gateway.yml)

2023-12-21 21:43 UTC, AlexanderSehr requested changes
Requires update to codeowners file (& potential creation of teams)

2023-12-21 21:47 UTC, AlexanderSehr commented on avm/res/network/nat-gateway/tests/e2e/max/main.test.bicep
> +          }
```suggestion
      {
        roleDefinitionIdOrName: 'Owner'
        principalId: nestedDependencies.outputs.managedIdentityPrincipalId
        principalType: 'ServicePrincipal'
      }
      {
        roleDefinitionIdOrName: 'b24988ac-6180-42a0-ab88-20f7382dd24c'
        principalId: nestedDependencies.outputs.managedIdentityPrincipalId
        principalType: 'ServicePrincipal'
      }
      {
        roleDefinitionIdOrName: subscriptionResourceId('Microsoft.Authorization/roleDefinitions', 'acdd72a7-3385-48ef-bd42-f606fba81ae7')
        principalId: nestedDependencies.outputs.managedIdentityPrincipalId
        principalType: 'ServicePrincipal'
      }
```

As reference for other users.

2023-12-21 21:52 UTC, AlexanderSehr commented on avm/res/network/nat-gateway/tests/e2e/prefixCombined/main.test.bicep
> +    }
```suggestion
```

Should be removed as unrelated to test scenario and covered by another test case. If also the other role assignment is removed it enables you to remove the dependency.

2023-12-21 21:53 UTC, AlexanderSehr commented on avm/res/network/nat-gateway/tests/e2e/prefixCombined/main.test.bicep
> +param enableTelemetry bool = true
```suggestion
```

2023-12-21 21:53 UTC, AlexanderSehr commented on avm/res/network/nat-gateway/tests/e2e/prefixCombined/main.test.bicep
> +    enableTelemetry: enableTelemetry
```suggestion
```

2023-12-21 21:54 UTC, AlexanderSehr commented on avm/res/network/nat-gateway/tests/e2e/waf-aligned/main.test.bicep
> +        ]
```suggestion
```

Should be removed as it's not required to be WAF-aligned. You can also remove the dependency

2023-12-21 21:54 UTC, AlexanderSehr commented on avm/res/network/nat-gateway/tests/e2e/waf-aligned/main.test.bicep
> +    enableTelemetry: enableTelemetry
```suggestion
```

2023-12-21 21:54 UTC, AlexanderSehr commented on avm/res/network/nat-gateway/tests/e2e/waf-aligned/main.test.bicep
> +param enableTelemetry bool = true
```suggestion
```

2023-12-21 21:55 UTC, AlexanderSehr commented on avm/res/network/nat-gateway/tests/e2e/max/main.test.bicep
> +param enableTelemetry bool = true
```suggestion
```

2023-12-21 21:55 UTC, AlexanderSehr commented on avm/res/network/nat-gateway/tests/e2e/max/main.test.bicep
> +    enableTelemetry: enableTelemetry
```suggestion
```

2023-12-21 21:56 UTC, AlexanderSehr commented on avm/res/network/nat-gateway/main.bicep
> +module publicIPAddresses '../public-ip-address/main.bicep' = [for (publicIPAddressObject, index) in (publicIPAddressObjects ?? []): {
Must reference the published module

2023-12-21 21:57 UTC, AlexanderSehr commented on avm/res/network/nat-gateway/main.bicep
> +var enableReferencedModulesTelemetry = false
```suggestion
```

2023-12-26 01:23 UTC, eriqua commented on .github/workflows/avm.res.network.nat-gateway.yml
Please uncomment related line in CODEOWNERS file

2023-12-27 13:21 UTC, eriqua commented on .github/CODEOWNERS
> +/avm/res/network/nat-gateway/ @Azure/avm-res-network-natgateway-module-owners-bicep @Azure/avm-core-team-technical-bicep
The `avm-res-network-natgateway-module-owners-bicep` team should be added as member of `avm-technical-reviewers-bicep`

2023-12-28 00:16 UTC, eriqua commented on .github/CODEOWNERS
> +/avm/res/network/nat-gateway/ @Azure/avm-res-network-natgateway-module-owners-bicep @Azure/avm-core-team-technical-bicep
Solved

2023-12-28 10:14 UTC, AlexanderSehr commented on avm/res/network/nat-gateway/tests/e2e/prefixCombined/main.test.bicep
> +}
```suggestion
```

2023-12-28 10:15 UTC, AlexanderSehr commented on avm/res/network/nat-gateway/tests/e2e/prefixCombined/main.test.bicep
> +    }
```suggestion
    ]
```

2023-12-28 10:15 UTC, AlexanderSehr commented on avm/res/network/nat-gateway/tests/e2e/prefixCombined/main.test.bicep
> +
```suggestion
```

2023-12-28 10:15 UTC, AlexanderSehr commented on avm/res/network/nat-gateway/tests/e2e/prefixCombined/main.test.bicep
> +    }
```suggestion
```

2023-12-28 23:49 UTC, AlexanderSehr commented on avm/res/network/nat-gateway/tests/e2e/prefixCombined/main.test.bicep
> +    }
```suggestion
```

2023-12-29 22:08 UTC, AlexanderSehr requested changes
After the latest changes please re-run the pipeline again and we can merge the PR in :)

2024-01-01 11:37 UTC, AlexanderSehr approved these changes

2024-01-01 11:38 UTC, merged