feat: `avm/res/compute/disk`
Azure/bicep-registry-modules pull request #794
Opened 2024-01-12 05:44 UTC by segraef

[![avm.res.compute.disk](https://github.com/segraef/bicep-registry-modules/actions/workflows/avm.res.compute.disk.yml/badge.svg?branch=avm%2Fres%2Fnew)](https://github.com/segraef/bicep-registry-modules/actions/workflows/avm.res.compute.disk.yml)

2024-01-12 10:33 UTC, AlexanderSehr requested changes
Requires uncommenting in the `/.github/CODEOWNERS` file

2024-01-12 10:40 UTC, AlexanderSehr commented on .github/workflows/avm.res.compute.disk.yml
> +  modulePath: "avm/res/network/network-security-group"
```suggestion
  modulePath: "avm/res/compute/disk"
```

2024-01-12 10:44 UTC, segraef commented
> Requires uncommenting in the `/.github/CODEOWNERS` file

done

2024-01-12 10:52 UTC, AlexanderSehr commented on avm/res/compute/disk/main.bicep
> +@description('Optional. Enable telemetry via a Globally Unique Identifier (GUID).')
```suggestion
@description('Optional. Enable/Disable usage telemetry for module.')
```

2024-01-12 11:04 UTC, AlexanderSehr commented on avm/res/compute/disk/main.bicep
> +    osType: empty(osType) ? any(null) : osType
```suggestion
    osType: !empty(osType) ? osType : any(null)
```

2024-01-12 11:05 UTC, AlexanderSehr commented on avm/res/compute/disk/main.bicep
> +    hyperVGeneration: empty(osType) ? null : hyperVGeneration
```suggestion
    hyperVGeneration: !empty(osType) ? hyperVGeneration : null
```

2024-01-12 11:05 UTC, AlexanderSehr commented on avm/res/compute/disk/main.bicep
> +      }
```suggestion
      imageReference: createOption == 'FromImage' ? {
        id: imageReferenceId
      } : null
```

2024-01-12 11:06 UTC, AlexanderSehr commented on avm/res/compute/disk/main.bicep
> +    }
```suggestion
    supportedCapabilities: !empty(osType) ? {
      acceleratedNetwork: acceleratedNetwork
      architecture: !empty(architecture) ? architecture : null
    } : {}
```

2024-01-12 11:25 UTC, AlexanderSehr commented on avm/res/compute/disk/tests/e2e/import/main.test.bicep
> +    ]
```suggestion
```

2024-01-12 11:25 UTC, AlexanderSehr commented on avm/res/compute/disk/tests/e2e/import/main.test.bicep
> +    }
```suggestion
```

2024-01-12 11:26 UTC, AlexanderSehr commented on avm/res/compute/disk/tests/e2e/image/main.test.bicep
> +    }
```suggestion
```

2024-01-12 23:07 UTC, eriqua commented on .github/workflows/avm.res.compute.disk.yml
> +    runs-on: ubuntu-20.04
```suggestion
    runs-on: ubuntu-latest
```

2024-01-15 13:19 UTC, AlexanderSehr approved these changes

2024-01-15 13:19 UTC, merged