feat: `avm/res/consumption/budget`
Azure/bicep-registry-modules pull request #796
Opened 2024-01-12 05:46 UTC by segraef

[![avm.res.consumption.budget](https://github.com/segraef/bicep-registry-modules/actions/workflows/avm.res.consumption.budget.yml/badge.svg?branch=avm%2Fres%2Fnew)](https://github.com/segraef/bicep-registry-modules/actions/workflows/avm.res.consumption.budget.yml)

2024-01-12 10:33 UTC, AlexanderSehr requested changes
Requires uncommenting in the `/.github/CODEOWNERS` file

2024-01-12 10:43 UTC, segraef commented
> Requires uncommenting in the `/.github/CODEOWNERS` file

done

2024-01-12 10:52 UTC, AlexanderSehr commented on avm/res/consumption/budget/main.bicep
> +@description('Optional. Enable telemetry via a Globally Unique Identifier (GUID).')
```suggestion
@description('Optional. Enable/Disable usage telemetry for module.')
```

2024-01-12 11:01 UTC, AlexanderSehr commented on avm/res/consumption/budget/main.bicep
> +    contactGroups: empty(actionGroups) ? null : array(actionGroups)
```suggestion
    contactEmails: !empty(contactEmails) ? array(contactEmails) : null
    contactRoles: !empty(contactRoles) ? array(contactRoles) : null
    contactGroups: !empty(actionGroups) ? array(actionGroups) : null
```

2024-01-12 23:09 UTC, eriqua commented on .github/workflows/avm.res.consumption.budget.yml
> +    runs-on: ubuntu-20.04
```suggestion
    runs-on: ubuntu-latest
```

2024-01-15 13:20 UTC, AlexanderSehr approved these changes

2024-01-15 13:20 UTC, merged